### ISSUE TITLE
Temporary luarocks build directory on LUA_PATH

### ISSUE THREAD

**Issue by bjornbm** [oploadk/localua#3]
I noticed that that temporary build directory used by localua ends up in LUA_PATH:

./.localua/bin/luarocks path
LUA_PATH='**/private/tmp/localua-MwI1H6/luarocks-3.9.2/src/?.lua;**/Users/bjorn/repos/.localua/share/lua/5.4/?.lua;/Users/bjorn/repos/.localua/share/lua/5.4/?/init.lua;/Users/bjorn/repos/.localua/lib/lua/5.4/?.lua;/Users/bjorn/repos/.localua/lib/lua/5.4/?/init.lua;./?.lua;./?/init.lua;/Users/bjorn/.luarocks/share/lua/5.4/?.lua;/Users/bjorn/.luarocks/share/lua/5.4/?/init.lua'

Probably this is due to how luarocks' builds itself rather than localua? In any case, it is very unlikely to cause any trouble so closing with “won't fix” is a pragmatic response to this issue (which I wrote mainly to document this quirk).

**Comment by catwell** [comment]
I agree that this should not be in the path. I will check it out when I have some time.

**Comment by catwell** [comment]
Fixed by #5.
